apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-2
  labels:
    app: web
spec:
  selector:
    matchLabels:
      project: http-web
  template:
    metadata:
      labels:
        project: http-web
    spec:
      containers:
        - name: web1
          image: arachidi/myappk8s:latest
          ports: 
            - containerPort: 80
